apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  labels:
    app: java-app
spec:
  replicas: 2  # Adjust the number of replicas if needed
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      annotations:
        admission.datadoghq.com/java-lib.version: "1.47.3"
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: ashutoshkharel/java-app:jv78  # Replace with your image and tag
          ports:
            - containerPort: 8080  # Expose port 8080 inside the container (Spring Boot default)
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: DD_AGENT_HOST
              value: "datadog-agent"
            - name: DD_TRACE_AGENT_PORT
              value: "8126"
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
spec:
  selector:
    app: java-app  # The service will match the deployment's label
  ports:
    - protocol: TCP
      port: 8080          # External port the service will listen on
      targetPort: 9098   # Port inside the container where the app is running
  type: ClusterIP  # Exposes the service externally, can be changed to ClusterIP for internal access
