filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - config:
            - type: container
              format: docker
              paths:
                - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
              processors:
                - decode_json_fields:
                    fields: ["message"]
                    target: ""
                    overwrite_keys: true
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
 # ssl.certificate_authorities: ["/usr/share/filebeat/config/certs/http_ca.crt"]
 # ssl.verification_mode: none

  username: "*****************"
  password: "*****************"

logging.metrics.enabled: false
