registry: "gcr.io/datadoghq"
datadog:
  apiKeyExistingSecret: "datadog-secret"
  site: "datadoghq.com"
  tags:
    - env: test
  clusterName: "default"
  kubelet:
    tlsVerify: false
  apm:
    portEnabled: true
    enabled: true
    nonLocalTraffic: true
    instrumentation:
      enabled: true
      libVersions:
        java: "1"
        dotnet: "3"
        python: "2"
        js: "5"
  profiling:
    enabled: true

#  securityAgent:
#    runtime:
#      enabled: true
#    compliance:
#      enabled: true
#  sbom:
#    containerImage:
#      enabled: true
#    host:
#      enabled: true
          
  logs:
    enabled: true
    containerCollectAll: true
  processAgent:
    enabled: true
    processCollection: true
    runInCoreAgent: true
  kubernetes:
    enabled: true
    orchestrator:
      enabled: true

  asm:
    threats:
      enabled: true
    sca:
      enabled: true
    iast:
      enabled: true
  serviceMonitoring:
    enabled: true
  networkMonitoring:
    enabled: true



# To setup squid proxy in datadog-agent and clusteragent pods 

apm:
  instrumentation:
    enabled: true
    targets:
      - name: "all"
        namespaceSelector: {}
        podSelector: {}
        
agents:
  image:
    tagSuffix: jmx
  tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/controlplane
      operator: Exists
    - effect: NoExecute
      key: node-role.kubernetes.io/etcd
      operator: Exists

  dogstatsd:
    port: 8125
    useHostPort: true
    nonLocalTraffic: true

#  env:
#    - name: DD_PROXY_HTTP
#      value: http://192.168.0.103:3128
#    - name: DD_PROXY_HTTPS
#      value: http://192.168.0.103:3128
#    - name: DD_PROXY_NO_PROXY
#      value: "localhost,127.0.0.1,*.svc,.cluster.local,kubernetes.default"

clusterAgent:
  enabled: true
  admissionController:
    enabled: true
#    configMode: service
#    validation:
#      enabled: true
#    mutation:
#      enabled: true
    mutateUnlabelled: true
#    webhookName: datadog-webhook

#  env:
#    - name: DD_PROXY_HTTP
#      value: http://192.168.0.103:3128
#    - name: DD_PROXY_HTTPS
#      value: http://192.168.0.103:3128
#    - name: DD_PROXY_NO_PROXY
#      value: "localhost,127.0.0.1,*.svc,.cluster.local,kubernetes.default"
