apiVersion: v1
kind: Service
metadata:
  name: notes-app
  labels:
    name: notes-app-service
    app: java-tutorial-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  selector:
    name: notes-app-pod
    app: java-tutorial-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deploy
  labels:
    name: notes-app-deploy
    app: java-tutorial-app
#    tags.datadoghq.com/env: "test"
#    tags.datadoghq.com/service: "notes-app"
#    tags.datadoghq.com/version: "0.0.1"
spec:
  replicas: 2
  selector:
    matchLabels:
      name: notes-app-pod
      app: java-tutorial-app
  template:
    metadata:
      name: notes-app-pod
      labels:
        admission.datadoghq.com/enabled: "true"
        name: notes-app-pod
        app: java-tutorial-app
        tags.datadoghq.com/env: "test"
        tags.datadoghq.com/service: "notes-app"
        tags.datadoghq.com/version: "0.0.1"
#      annotations:
        # Datadog APM (Automatic Instrumentation)
#        admission.datadoghq.com/java-lib.version: "v1.48.0"  # Specify the Java APM agent version
#        ad.datadoghq.com/notes-app.apm.enabled: "true"  # Enable APM
        # Datadog Log Collection
#        ad.datadoghq.com/notes-app.logs: >-
#          [{
#            "source": "java",
#            "service": "notes",
#            "log_processing_rules": [{
#              "type": "multi_line",
#              "name": "log_start_with_date",
#              "pattern": "\\d{2}-\\d{2}-\\d{4}\\s\\d{2}:\\d{2}:\\d{2}.\\d{3}"
#            }]
#          }]
    spec:
      containers:
        - name: notes-app
          image: ashutoshkharel/java-app:update
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DD_PROFILING_ENABLED
              value: "true"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_APPSEC_ENABLED
              value: "true"
            - name: DD_IAST_ENABLED
              value: "true"
            - name: DD_APPSEC_SCA_ENABLED
              value: "true"
            - name: DD_TRACE_SAMPLE_RATE
              value: "1"
            - name: DD_DATA_STREAMS_ENABLED
              value: "true"
            - name: DD_TRACE_REMOVE_INTEGRATION_SERVICE_NAMES_ENABLED
              value: "true"
            - name: DD_TRACE_SQS_BODY_PROPAGATION_ENABLED
              value: "true"
#            - name: DD_GIT_COMMIT_SHA
#              value: 4dfdfc666ce3eac8e1bdcab5c9684ae54c528457
#            - name: DD_GIT_REPOSITORY_URL
#              value: https://github.com/ayushka-710/git.git
#            - name: CALENDAR_HOST
#              value: calendar-app
            - name: DD_AGENT_HOST
              value: "datadog-agent"  # The name of the Datadog Agent
            - name: DD_TRACE_AGENT_PORT
              value: "8126"  # Default port for Datadog tracing agent
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
#            - name: DD_LOGS_INJECTION
#              value: "true"  # Enable log injection into Datadog
#            - name: JAVA_OPTS
#              value: "-javaagent:/opt/datadog/dd-java-agent.jar"  # Path to Datadog Java Agent
#      restartPolicy: Always
