dataDirectory: /var/lib/humio-log-collector
sources:
  syslog_tcp_1514:
    type: syslog
    mode: tcp
    port: 1514
    sink: humio
#  var_log:
#    type: file
#    include: /var/log/*
#    exclude: /var/log/*.gz
#    sink: humio
sinks:
  humio:
    type: hec
    token: **************************************
    url: ****************************************

